### ISSUE TITLE
Undo Move

### ISSUE THREAD

**Issue by anthonylee83** [zacharytamas/bakers-dozen#9]
## Undo Move
Create an option to undo a move.  @zacharytamas would adding the current boradState to a boardHistory property work for holding a version history on this?

**Comment by zacharytamas** [comment]
Yeah as a simple approach that would probably work. I guess you mean an array that holds old versions of the `boardState`? Then to undo you'd just pop one off and set it as the `boardState`?

**Comment by anthonylee83** [comment]
Yeah, that's the quickest way I could think of to implement it.

**Comment by anthonylee83** [comment]
Implemented.
